FROM python:3.10-slim AS python-base
RUN apt-get update && apt-get install -y curl
ARG APP_DIR=/app
WORKDIR $APP_DIR
ADD ./LBS/app $APP_DIR
ADD ./LBS/req /req
RUN pip install --upgrade pip && \
    pip install -r /req/requirements.txt && \
    rm -rf /req
EXPOSE 5000
CMD ["/app/runserver.sh"]